ADD_SCENE(flick, main_menu, MainMenu)
ADD_SCENE(flick, eula, EULA)
ADD_SCENE(flick, password, Password)
ADD_SCENE(flick, check_flicked, CheckFlicked)
ADD_SCENE(flick, do_flick, DoFlick)
ADD_SCENE(flick, un_flick, UnFlick)
